### ISSUE TITLE
Please rename package

### ISSUE THREAD

**Issue by Seldaek** [netgusto/Symfony-BootcampBundle#1]
I was wondering if it would be possible for you to rename this symfony/bootcamp-bundle on packagist to something out of the symfony namespace like netgusto/bootcamp-bundle. You already have all your other bundles in that vendor so that would make sense for you, and remove some potential confusion from packagist users.

You can rename in composer.json, re-submit it to packagist with the new name, then mark the old package as abandoned and point to the new one's name so your users get a notification and they can migrate to the new name. After a while we will maybe be able to delete the old one if nobody uses it anymore.

**Comment by Tobion** [comment]
@netgusto any news about this one? Is it still maintained?

**Comment by netgusto** [comment]
Yes. Haven't given the time to react though. Will do asap.

**Comment by netgusto** [comment]
But what's the reason for this ? It seems legit as an extension to the SF core, besides no hack involved to get there on packagist.

**Comment by Tobion** [comment]
See symfony/symfony#14574. It's not official from symfony.

**Comment by netgusto** [comment]
Okey.

**Comment by Tobion** [comment]
ping

**Comment by Seldaek** [comment]
@netgusto there is really no reason for your package to be under the symfony namespace, using `netgusto/bootcamp-bundle` would be better IMO, as said above you can rename the package in composer.json, re-submit it to packagist with the new name, then mark the old package as abandoned and point to the new one's name so your users get a notification and they can migrate to the new name. After a while we will maybe be able to delete the old one if nobody uses it anymore.

Can we please reach a resolution? It'll take you 5min and would help clean things up on packagist.

**Comment by jakzal** [comment]
@netgusto ping :) any progress?

**Comment by netgusto** [comment]
Hey @jakzal @Seldaek @Tobion ! It's done. The package has been marked as abandoned, and replaced by netgusto/bootcamp-bundle.

Thank you for not loosing your patience.

**Comment by xabbuh** [comment]
Thank you @netgusto!
